### ISSUE TITLE
[1.10.2] Crash on startup

### ISSUE THREAD

**Issue by SeriousCreeper** [FeldrinH/Shadowmancy#1]
Heya, 

just was going to try out the mod but unfortunately it crashes on startup: http://pastebin.com/7UWM8s1q 

Let me know if you need any other information!
Looking forward to use this, it's gonna be fun and brutal _queue evil laughter_

Thanks,
-SC

**Comment by FeldrinH** [comment]
Fixed. Should have checked with actual Minecraft before releasing.
Hotfix will be live as soon as CurseForge approves it.

**Comment by SeriousCreeper** [comment]
Thanks a lot, seems to work great! :D
