### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by TECHTERROR731** [FeldrinH/Shadowmancy#5]
When I modify the config to, for example, make the light threshold 4 instead of 7, nothing changes and I still get damaged in 7 light level.

**Comment by FeldrinH** [comment]
What Minecraft and mod version are you using?

**Comment by TECHTERROR731** [comment]
last version of the mod in minecraft 1.7.10

**Comment by Gintas2002** [comment]
> What Minecraft and mod version are you using?

Fix your mod, 5 years later still damage at light level 7 whatever i change in the config...

**Comment by FeldrinH** [comment]
I haven't really been maintaining this mod for the last 5 years and my interests are currently elsewhere, so I doubt I will start to maintain it again anytime soon.

That said I did take a look at this bug and I think I fixed it. I have released version 1.7.10-0.8.1 with the fix. Other Minecraft versions should not have been affected.
